# Generated by Django 4.0.1 on 2022-02-20 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_uf_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cidade'),
        ),
    ]
