# Generated by Django 4.0.1 on 2022-02-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
