# Generated by Django 4.0.1 on 2022-02-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_servico_valor_alter_servico_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='categ',
        ),
    ]
